---
name: pre-commit-check
on:
  push:
    branches:
      - main
      - master
      - prod
      - develop

jobs:
  pre-commit-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      - name: Install prerequisites
        run: ./bin/install-ubuntu.sh
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: ~0.12.29
      - name: initialize Terraform
        run: terraform init --backend=false
      - name: pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        env:
          AWS_DEFAULT_REGION: us-east-1
          # many of these are covered by better reviewdog linters below
          SKIP: >-
            terraform_tflint_deep,
            no-commit-to-branch,
            terraform_tflint_nocreds,
            terraform_tfsec
      - uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        if: ${{ failure() }}
        with:
          commit_message: Apply automatic changes
          commit_options: "--no-verify"
          # Optional commit user and author settings
          commit_user_name: Linter Bot
          commit_user_email: noreply@rhythmictech.com
          commit_author: Linter Bot <actions@github.com>
