---
name: tflint
on:
  push:
    branches:
      - main
      - master
      - prod
      - develop

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - name: setup Terraform
        uses: hashicorp/setup-terraform@ed3a0531877aca392eb870f440d9ae7aba83a6bd # v1.4.0
        with:
          terraform_version: ~0.12.29
      - name: Terraform init
        run: terraform init --backend=false
      - name: tflint
        uses: reviewdog/action-tflint@54a5e5aed57dcfbb4662ec548de876df33d6288d # v1.25.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          filter_mode: nofilter
          flags: --module
          level: error
